#!/bin/bash
set -e

echo "=== Netlify Flutter Web Build Starting ==="

# Install Flutter if not already installed
if [ ! -d "$HOME/flutter" ]; then
  echo "Installing Flutter..."
  git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
fi

# Add Flutter to PATH
export PATH="$HOME/flutter/bin:$PATH"

# Enable Flutter web
flutter config --enable-web

# Verify Flutter installation
flutter --version

# Get Flutter dependencies
flutter pub get

# Build the Flutter web app
flutter build web --release

echo "=== Flutter Web Build Completed ==="
