name: rivalis
description: A Flutter web app with Firebase integration
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.5.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^5.3.0

  # Other common Flutter packages
  provider: ^6.0.7
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
