name: rivalis_app
description: A Flutter application.
publish_to: "none" # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.13.0
  characters: ^1.4.1
  fake_async: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  leak_tracker: ^11.0.2
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  lints: ^6.0.0

flutter:
  uses-material-design: true
