name: rivalis_fitness
description: A Flutter fitness workout app with card-based exercises
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  provider: 6.1.6
  shared_preferences: 2.2.1
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.1.1
  fake_async: 1.3.0
  async: 3.3.2
  leak_tracker_flutter_testing: 0.1.6
  leak_tracker: 0.2.0
  material_color_utilities: 0.2.1
  meta: 1.9.1
  test_api: 0.5.2
  vector_math: 2.2.0
  vm_service: 10.1.0

flutter:
  uses-material-design: true
